#ifndef _BOX2D_HELPERS_H
#define _BOX2D_HELPERS_H

#define DISPLAY_WIDTH				960
#define DISPLAY_HEIGHT				544

#define BOX2D_ABFW_SCALE 100.0f
#define BOX2D_ABFW_OFFSET_X DISPLAY_WIDTH*0.5f
#define BOX2D_ABFW_OFFSET_Y 0.0f
#define BOX2D_ABFW_POS_X(x) ((x)*BOX2D_ABFW_SCALE + BOX2D_ABFW_OFFSET_X)
#define BOX2D_ABFW_POS_Y(y) (DISPLAY_HEIGHT - ((y)*BOX2D_ABFW_SCALE + BOX2D_ABFW_OFFSET_Y))
#define BOX2D_ABFW_SIZE(s) ((s)*BOX2D_ABFW_SCALE)
#define ABFW_BOX2D_POS_X(x) (((x) - BOX2D_ABFW_OFFSET_X)/BOX2D_ABFW_SCALE)
#define ABFW_BOX2D_POS_Y(y) (((y) - DISPLAY_HEIGHT+BOX2D_ABFW_OFFSET_Y)/-BOX2D_ABFW_SCALE)
#define ABFW_BOX2D_SIZE(s) ((s)/BOX2D_ABFW_SCALE)
#define DEGREES_RADIANS(d) ((d)*(3.14159/180))

#endif // _BOX2D_HELPERS_H